services:
  phpenvgauss:
    build:
      context: .
    ports:
      - 81:80
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    links:
      - pythonenvgauss
    container_name: phpenvgauss
  pythonenvgauss:
    build:
      context: .
      dockerfile: DockerfilePython
    volumes:
      - ./flask:/app
    ports:
      - 82:5000
    working_dir: /app
    container_name: pythonenvgauss
